// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgAlbumsOutline = (props: IconProps) => (
  <Icon
    title={'SvgAlbumsOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M19.647 8.25H4.353C3.606 8.25 3 8.856 3 9.603v9.294c0 .747.606 1.353 1.353 1.353h15.294c.747 0 1.353-.606 1.353-1.353V9.603c0-.747-.606-1.353-1.353-1.353z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
        <path d="M6.75 3.75h10.5-10.5zM5.25 6h13.5-13.5z" fill="currentColor" />
        <path
          d="M5.25 6h13.5m-12-2.25h10.5-10.5z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
      </svg>
    }
  />
);

export default SvgAlbumsOutline;
