// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgAppleSolid = (props: IconProps) => (
  <Icon
    title={'SvgAppleSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M15.75 2c.18 1.215-.315 2.405-.967 3.247-.698.903-1.901 1.602-3.066 1.565-.213-1.163.332-2.361.994-3.167.727-.889 1.973-1.57 3.04-1.645zm3.502 17.099c.6-.921.825-1.386 1.291-2.425-3.392-1.29-3.935-6.113-.578-7.964-1.024-1.284-2.463-2.028-3.822-2.028-.978 0-1.649.255-2.259.487-.508.194-.973.371-1.54.371-.612 0-1.154-.194-1.721-.398-.624-.223-1.278-.458-2.09-.458-1.525 0-3.147.931-4.176 2.524-1.446 2.242-1.2 6.458 1.146 10.05C6.34 20.543 7.46 21.987 8.925 22c.608.006 1.012-.175 1.45-.372.501-.224 1.045-.469 1.988-.474.948-.005 1.484.242 1.979.47.426.197.821.379 1.424.372 1.466-.011 2.647-1.612 3.486-2.897z"
          fill="#0B0B0A"
        />
      </svg>
    }
  />
);

export default SvgAppleSolid;
