// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgArrowRedoCircleOutline = (props: IconProps) => (
  <Icon
    title={'SvgArrowRedoCircleOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12.511 15.363v-1.75c-2.675 0-3.961.632-5.09 1.814-.253.264-.703.062-.67-.302.256-2.88 1.6-5.488 5.76-5.488v-1.75a.39.39 0 01.656-.281l3.962 3.738a.384.384 0 010 .56l-3.957 3.739a.39.39 0 01-.66-.28z"
          fill="currentColor"
        />
        <path
          d="M3 12c0 4.969 4.031 9 9 9s9-4.031 9-9-4.031-9-9-9-9 4.031-9 9z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
      </svg>
    }
  />
);

export default SvgArrowRedoCircleOutline;
