// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgArrowUndoCircleOutline = (props: IconProps) => (
  <Icon
    title={'SvgArrowUndoCircleOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M11.488 15.363v-1.75c2.676 0 3.962.632 5.09 1.814.253.264.703.062.67-.302-.256-2.88-1.6-5.488-5.76-5.488v-1.75a.39.39 0 00-.658-.281l-3.96 3.738a.384.384 0 000 .56l3.958 3.739a.39.39 0 00.66-.28z"
          fill="currentColor"
        />
        <path
          d="M12 3c-4.969 0-9 4.031-9 9s4.031 9 9 9 9-4.031 9-9-4.031-9-9-9z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
      </svg>
    }
  />
);

export default SvgArrowUndoCircleOutline;
