// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgArrowRedoOutline = (props: IconProps) => (
  <Icon
    title={'SvgArrowRedoOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M21 12l-8.25-7.875v4.5C4.855 8.625 3 14.286 3 19.875c2.279-2.918 4.294-4.5 9.75-4.5v4.5L21 12z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgArrowRedoOutline;
