// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgArrowUndoOutline = (props: IconProps) => (
  <Icon
    title={'SvgArrowUndoOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M11.25 19.875v-4.5c5.456 0 7.471 1.582 9.75 4.5 0-5.589-1.855-11.25-9.75-11.25v-4.5L3 12l8.25 7.875z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgArrowUndoOutline;
