// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgArrowCircleRightOutline = (props: IconProps) => (
  <Icon
    title={'SvgArrowCircleRightOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M3 12c0 4.969 4.031 9 9 9s9-4.031 9-9-4.031-9-9-9-9 4.031-9 9z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
        <path
          d="M10.125 16.5l4.5-4.5-4.5-4.5"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgArrowCircleRightOutline;
