// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgAttachmentOutline = (props: IconProps) => (
  <Icon
    title={'SvgAttachmentOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M20.304 10.951l-8.316 8.316s-3.86 3.86-7.424.297C1 16 4.86 12.139 4.86 12.139l8.612-8.612s2.376-2.376 4.752 0 0 4.751 0 4.751L9.91 16.594s-1.188 1.188-2.376 0 0-2.376 0-2.376l7.721-7.722"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgAttachmentOutline;
