// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgAwardRibbonOutline = (props: IconProps) => (
  <Icon
    title={'SvgAwardRibbonOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12.002 15.14a6.17 6.17 0 100-12.34 6.17 6.17 0 000 12.34z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12.004 15.143L15.5 21.2l1.644-3.323 3.7.238-3.497-6.056M6.656 12.058L3.16 18.114l3.7-.238 1.643 3.323L12 15.143"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgAwardRibbonOutline;
