// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgAwardRibbon2Outline = (props: IconProps) => (
  <Icon
    title={'SvgAwardRibbon2Outline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12 13.5a6 6 0 100-12 6 6 0 000 12z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M6.734 10.679L2.25 18.75l4.072-.02a.75.75 0 01.647.366L9 22.5l4.14-9.109M17.182 10.5l4.568 8.25-4.072-.02a.75.75 0 00-.647.366L15 22.5l-3-6.6M12 10.5a3 3 0 100-6 3 3 0 000 6z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgAwardRibbon2Outline;
