// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgBackspaceOutline = (props: IconProps) => (
  <Icon
    title={'SvgBackspaceOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M6.337 18.288a1.349 1.349 0 001.016.462h11.544a1.36 1.36 0 001.353-1.353V6.603a1.36 1.36 0 00-1.353-1.353H7.353a1.352 1.352 0 00-1.015.461L2.172 12l4.165 6.286v.002z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
        <path
          d="M15.781 15.11L9.687 9.015m6.094 0L9.687 15.11l6.094-6.095zm0 6.095L9.687 9.015l6.094 6.095zm0-6.095L9.687 15.11l6.094-6.095z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgBackspaceOutline;
