// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgBarChartOutline = (props: IconProps) => (
  <Icon
    title={'SvgBarChartOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M1.5 1.5v20.25a.75.75 0 00.75.75H22.5"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M7.313 10.5H5.438a.937.937 0 00-.938.938v7.124c0 .518.42.938.938.938h1.875c.517 0 .937-.42.937-.938v-7.125a.937.937 0 00-.938-.937zM14.063 8.25h-1.876a.937.937 0 00-.937.938v9.374c0 .518.42.938.938.938h1.874c.518 0 .938-.42.938-.938V9.188a.937.937 0 00-.938-.937zM20.796 5.25H18.92a.938.938 0 00-.938.938v12.375c0 .517.42.937.938.937h1.875c.517 0 .937-.42.937-.938V6.188a.937.937 0 00-.937-.937z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgBarChartOutline;
