// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgBellOutline = (props: IconProps) => (
  <Icon
    title={'SvgBellOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M4.696 9.38c-.001-.89.188-1.77.558-2.592a6.735 6.735 0 011.597-2.195 7.39 7.39 0 012.39-1.461 7.861 7.861 0 012.815-.502c4.027.028 7.249 3.113 7.249 6.835v.665c0 3.358.762 5.306 1.433 6.371a.706.706 0 01.005.751.785.785 0 01-.297.276.867.867 0 01-.408.102H3.962a.866.866 0 01-.408-.102.783.783 0 01-.297-.276.704.704 0 01.005-.751c.671-1.065 1.434-3.014 1.434-6.371v-.75z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M8.745 17.63v.75c0 .796.343 1.559.953 2.121.61.563 1.439.879 2.302.879s1.691-.316 2.302-.879c.61-.562.953-1.325.953-2.121v-.75"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgBellOutline;
