// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgBinOutline = (props: IconProps) => (
  <Icon
    title={'SvgBinOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M5.314 19.12l-.62-12.393h14.612l-.62 12.393a2.4 2.4 0 01-2.397 2.28H7.711a2.4 2.4 0 01-2.397-2.28zM8.632 6.162h6.736V5a2.4 2.4 0 00-2.4-2.4h-1.936a2.4 2.4 0 00-2.4 2.4v1.162z"
          stroke="currentColor"
          strokeWidth={1.2}
        />
        <path
          d="M3.27 6.448h17.46M14.381 11.683v3.968M9.62 11.683v3.968"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
        />
      </svg>
    }
  />
);

export default SvgBinOutline;
