// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgBookmarkOutline = (props: IconProps) => (
  <Icon
    title={'SvgBookmarkOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M16.5 2.25h-9A2.25 2.25 0 005.25 4.5v17.25l6.75-6 6.75 6V4.5a2.25 2.25 0 00-2.25-2.25z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgBookmarkOutline;
