// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgBriefcaseOutline = (props: IconProps) => (
  <Icon
    title={'SvgBriefcaseOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M20.25 6H3.75A2.25 2.25 0 001.5 8.25v10.5A2.25 2.25 0 003.75 21h16.5a2.25 2.25 0 002.25-2.25V8.25A2.25 2.25 0 0020.25 6z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
        <path
          d="M15 11.25v1.125a.375.375 0 01-.375.375h-5.25A.375.375 0 019 12.375V11.25M6.75 6V4.5A1.5 1.5 0 018.25 3h7.5a1.5 1.5 0 011.5 1.5V6H6.75zm15.75 5.25h-21 21z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgBriefcaseOutline;
