// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgBuildOutline = (props: IconProps) => (
  <Icon
    title={'SvgBuildOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M18.463 8.906a1.505 1.505 0 01-2.121 0l-1.246-1.245a1.504 1.504 0 010-2.122l2.82-2.82a.047.047 0 00-.015-.077c-1.82-.78-4.179-.383-5.677 1.105-1.433 1.422-1.515 3.562-.99 5.43a1.497 1.497 0 01-.424 1.504L3 17.813A2.258 2.258 0 106.188 21l7.212-7.828a1.496 1.496 0 011.481-.428c1.854.496 3.963.403 5.378-.993 1.523-1.5 1.851-4.152 1.113-5.669a.046.046 0 00-.034-.025.047.047 0 00-.041.013l-2.834 2.836z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
        <path
          d="M4.5 20.25a.75.75 0 100-1.5.75.75 0 000 1.5z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgBuildOutline;
