// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgButtonPlaySolid = (props: IconProps) => (
  <Icon
    title={'SvgButtonPlaySolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M17.769 11.58L6.99 4.116C6.589 3.84 6 4.09 6 4.536v14.928c0 .447.589.697.99.42L17.77 12.42a.498.498 0 000-.841z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgButtonPlaySolid;
