// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCalendarNumberOutline = (props: IconProps) => (
  <Icon
    title={'SvgCalendarNumberOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M19.5 3.75h-15A2.25 2.25 0 002.25 6v13.5a2.25 2.25 0 002.25 2.25h15a2.25 2.25 0 002.25-2.25V6a2.25 2.25 0 00-2.25-2.25z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
        <path
          d="M6 2.25v1.5m12-1.5v1.5m3.75 3.75H2.25m12 4.688l2.035-1.5h.215v7.874m-9.282-7.175c.203-.343.77-.887 1.774-.887 1.186 0 2.245.646 2.245 1.87a1.777 1.777 0 01-.522 1.278c-.512.525-1.294.725-1.721.725.483 0 1.368.227 1.948.82.37.378.542.911.542 1.503 0 1.307-1.103 2.054-2.443 2.054-1.133 0-1.828-.824-2.057-1.211"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCalendarNumberOutline;
