// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCalendarOutline = (props: IconProps) => (
  <Icon
    title={'SvgCalendarOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <rect
          x={1.867}
          y={3.034}
          width={12.267}
          height={11.098}
          rx={2}
          stroke="currentColor"
        />
        <path
          d="M4.933 1.866v1.168M11.066 1.866v1.168M1.867 5.955h12.266M4.627 8.876h.613M7.693 8.876h.614M10.76 8.876h.613M4.627 11.212h.613M7.693 11.212h.614M10.76 11.212h.613"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCalendarOutline;
