// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCalendar01Outline = (props: IconProps) => (
  <Icon
    title={'SvgCalendar01Outline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <rect
          x={2.9}
          y={4.535}
          width={18.2}
          height={16.467}
          rx={2}
          stroke="currentColor"
          strokeWidth={1.1}
        />
        <path
          d="M16.451 3v2.967M7.55 3v2.967M2.9 8.87h18.2"
          stroke="currentColor"
          strokeWidth={1.1}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCalendar01Outline;
