// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCameraDeactiveOutline = (props: IconProps) => (
  <Icon
    title={'SvgCameraDeactiveOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M19.854 17.04a1.627 1.627 0 001.176-.21 1.623 1.623 0 00.77-1.38V8.536a1.622 1.622 0 00-2.348-1.45l-3.786 1.892V7.904a2.644 2.644 0 00-2.644-2.644H8.074l1.2 1.2h3.748c.798 0 1.444.647 1.444 1.444v3.748l1.2 1.2V10.32l4.323-2.161a.422.422 0 01.61.377v6.914a.421.421 0 01-.61.378l-2.694-1.347 2.559 2.559zM3.007 1.593l-.3-.3L2 2l3.26 3.26h-.416A2.644 2.644 0 002.2 7.904v8.178a2.644 2.644 0 002.644 2.645h8.178a2.645 2.645 0 002.644-2.645v-.416L21 21l.7-.7L3 1.6l.007-.007zm11.46 12.873L6.46 6.46H4.844c-.798 0-1.444.647-1.444 1.444v8.178c0 .798.647 1.445 1.444 1.445h8.178c.798 0 1.444-.647 1.444-1.445v-1.616z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgCameraDeactiveOutline;
