// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCameraLiveSolid = (props: IconProps) => (
  <Icon
    title={'SvgCameraLiveSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M14.912 6H3.39C2.622 6 2 6.626 2 7.398v9.204c0 .772.622 1.397 1.389 1.398h11.523c.767 0 1.388-.626 1.39-1.398V7.398c-.002-.772-.623-1.397-1.39-1.398zM17.227 13.915l4.032 2.217a.5.5 0 00.74-.438V8.336a.5.5 0 00-.74-.438l-4.032 2.217v3.8z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgCameraLiveSolid;
