// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCameraOutline = (props: IconProps) => (
  <Icon
    title={'SvgCameraOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M16.432 6.97l-1.248-1.972c-.263-.307-.624-.498-1.028-.498H9.844c-.404 0-.765.191-1.028.498L7.568 6.969c-.263.307-.601.531-1.005.531H3.75A1.5 1.5 0 002.25 9v9a1.5 1.5 0 001.5 1.5h16.5a1.5 1.5 0 001.5-1.5V9a1.5 1.5 0 00-1.5-1.5h-2.766c-.405 0-.79-.224-1.052-.53z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12 16.5A3.75 3.75 0 1012 9a3.75 3.75 0 000 7.5z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
        <path
          d="M5.813 7.406V6.375H4.688v1.031"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCameraOutline;
