// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCameraReverseOutline = (props: IconProps) => (
  <Icon
    title={'SvgCameraReverseOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M16.432 6.97l-1.248-1.972c-.263-.307-.624-.498-1.028-.498H9.844c-.404 0-.765.191-1.028.498L7.568 6.969c-.263.307-.601.531-1.005.531H3.75A1.5 1.5 0 002.25 9v9a1.5 1.5 0 001.5 1.5h16.5a1.5 1.5 0 001.5-1.5V9a1.5 1.5 0 00-1.5-1.5h-2.766c-.405 0-.79-.224-1.052-.53z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M15.739 13.37v-.624a3.751 3.751 0 00-6.14-2.888M8.25 12.13v.624a3.75 3.75 0 006.128 2.897M5.812 7.406V6.375H4.688v1.031h1.125z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M16.688 12.75l-.938.938-.938-.938m-5.624 0l-.938-.938-.938.938h1.875z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCameraReverseOutline;
