// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCameraLiveOutline = (props: IconProps) => (
  <Icon
    title={'SvgCameraLiveOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M15.067 9.949l4.654-2.327a1.022 1.022 0 011.479.914v6.915a1.022 1.022 0 01-1.48.913l-4.653-2.326v-4.09zM13.022 5.86H4.844c-1.129 0-2.044.915-2.044 2.044v8.178c0 1.13.915 2.045 2.044 2.045h8.178c1.13 0 2.044-.916 2.044-2.045V7.904c0-1.129-.915-2.044-2.044-2.044z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCameraLiveOutline;
