// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCardOutline = (props: IconProps) => (
  <Icon
    title={'SvgCardOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M19.125 4.5H4.875A2.625 2.625 0 002.25 7.125v9.75A2.625 2.625 0 004.875 19.5h14.25a2.625 2.625 0 002.625-2.625v-9.75A2.625 2.625 0 0019.125 4.5z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M2.25 9h19.5-19.5zM6 14.063h2.25V15H6v-.938z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCardOutline;
