// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCaretForwardSolid = (props: IconProps) => (
  <Icon
    title={'SvgCaretForwardSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M8.91 19.406l7.645-6.552a1.126 1.126 0 000-1.708L8.91 4.594c-.73-.626-1.857-.107-1.857.854v13.106c0 .96 1.127 1.48 1.857.852z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgCaretForwardSolid;
