// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCaretDownCircleOutline = (props: IconProps) => (
  <Icon
    title={'SvgCaretDownCircleOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M16.052 11.167l-3.475 4.176a.75.75 0 01-1.153 0l-3.475-4.176a.75.75 0 01.576-1.23h6.95a.75.75 0 01.577 1.23z"
          fill="currentColor"
        />
        <path
          d="M21 12c0-4.969-4.031-9-9-9s-9 4.031-9 9 4.031 9 9 9 9-4.031 9-9z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
      </svg>
    }
  />
);

export default SvgCaretDownCircleOutline;
