// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCaretForwardCircleOutline = (props: IconProps) => (
  <Icon
    title={'SvgCaretForwardCircleOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M11.167 16.051l4.176-3.474a.75.75 0 000-1.154L11.167 7.95a.75.75 0 00-1.23.576v6.95a.75.75 0 001.23.576z"
          fill="currentColor"
        />
        <path
          d="M21 12c0-4.969-4.031-9-9-9s-9 4.031-9 9 4.031 9 9 9 9-4.031 9-9z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
      </svg>
    }
  />
);

export default SvgCaretForwardCircleOutline;
