// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCaretBackSolid = (props: IconProps) => (
  <Icon
    title={'SvgCaretBackSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M15.091 4.594l-7.646 6.552a1.125 1.125 0 000 1.708l7.646 6.552c.73.625 1.857.107 1.857-.854V5.446c0-.961-1.127-1.48-1.857-.852z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgCaretBackSolid;
