// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCaretDownSolid = (props: IconProps) => (
  <Icon
    title={'SvgCaretDownSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M4.594 8.91l6.552 7.645a1.125 1.125 0 001.708 0l6.552-7.646c.625-.73.107-1.857-.854-1.857H5.446c-.961 0-1.48 1.127-.852 1.857z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgCaretDownSolid;
