// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCaretUpCircleOutline = (props: IconProps) => (
  <Icon
    title={'SvgCaretUpCircleOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M16.051 12.833l-3.474-4.176a.75.75 0 00-1.154 0L7.95 12.833a.75.75 0 00.576 1.23h6.95a.75.75 0 00.576-1.23z"
          fill="currentColor"
        />
        <path
          d="M21 12c0-4.969-4.031-9-9-9s-9 4.031-9 9 4.031 9 9 9 9-4.031 9-9z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
      </svg>
    }
  />
);

export default SvgCaretUpCircleOutline;
