// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgChatbubbleOutline = (props: IconProps) => (
  <Icon
    title={'SvgChatbubbleOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M4.101 17.813c.056-.206-.067-.491-.185-.697a2.108 2.108 0 00-.12-.178 9.366 9.366 0 01-1.546-5.156C2.234 6.52 6.597 2.25 11.992 2.25c4.705 0 8.633 3.26 9.55 7.587.138.641.208 1.296.208 1.952 0 5.269-4.195 9.606-9.59 9.606-.858 0-2.016-.216-2.647-.393a17.713 17.713 0 01-1.425-.474A1.458 1.458 0 007 20.545l-3.18 1.148a.751.751 0 01-.218.057.45.45 0 01-.449-.457.744.744 0 01.028-.154l.92-3.326z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
      </svg>
    }
  />
);

export default SvgChatbubbleOutline;
