// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgChatboxOutline = (props: IconProps) => (
  <Icon
    title={'SvgChatboxOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M19.125 3H4.875A2.633 2.633 0 002.25 5.625v9a2.633 2.633 0 002.625 2.625H6.75V21l4.393-3.663a.375.375 0 01.24-.087h7.742a2.633 2.633 0 002.625-2.625v-9A2.633 2.633 0 0019.125 3v0z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgChatboxOutline;
