// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCheckmarkCircleOutline = (props: IconProps) => (
  <Icon
    title={'SvgCheckmarkCircleOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <g
          clipPath="url(#checkmark-circle-outline_svg__clip0)"
          stroke="currentColor"
          strokeWidth={1.3}
        >
          <path
            d="M21 12c0-4.969-4.031-9-9-9s-9 4.031-9 9 4.031 9 9 9 9-4.031 9-9z"
            strokeMiterlimit={10}
          />
          <path
            d="M16.5 8.25l-6.3 7.5-2.7-3"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </g>
        <defs>
          <clipPath id="checkmark-circle-outline_svg__clip0">
            <path fill="#fff" d="M0 0h24v24H0z" />
          </clipPath>
        </defs>
      </svg>
    }
  />
);

export default SvgCheckmarkCircleOutline;
