// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCheckmarkDoneOutline = (props: IconProps) => (
  <Icon
    title={'SvgCheckmarkDoneOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M21.75 6l-10.5 12-4.5-4.5m0 4.5l-4.5-4.5m15-7.5l-6.375 7.313"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCheckmarkDoneOutline;
