// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCloudUploadOutline = (props: IconProps) => (
  <Icon
    title={'SvgCloudUploadOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M15 17.24h3.563c2.578 0 4.687-1.37 4.687-3.919 0-2.55-2.484-3.819-4.5-3.918C18.333 5.415 15.422 2.99 12 2.99c-3.234 0-5.317 2.147-6 4.275C3.187 7.532.75 9.322.75 12.253c0 2.93 2.531 4.987 5.625 4.987H9"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M15 11.99l-3-3-3 3m3 9.02V9.74"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCloudUploadOutline;
