// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCloudyOutline = (props: IconProps) => (
  <Icon
    title={'SvgCloudyOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M4.696 11.306a.746.746 0 00.627-.621C5.934 6.825 8.735 4.5 12 4.5c3.032 0 5.053 1.986 5.856 4.078a.756.756 0 00.587.477c2.62.417 4.807 2.158 4.807 5.195 0 3.094-2.531 5.25-5.625 5.25H5.437C2.86 19.5.75 18.214.75 15.375c0-2.551 2.057-3.788 3.946-4.07z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCloudyOutline;
