// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCloudDoneOutline = (props: IconProps) => (
  <Icon
    title={'SvgCloudDoneOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M18.75 11.25C18.333 7.053 15.422 4.5 12 4.5 8.766 4.5 6.683 6.76 6 9 3.187 9.281.75 11.043.75 14.25c0 3.094 2.531 5.25 5.625 5.25h12.188c2.578 0 4.687-1.286 4.687-4.125 0-2.804-2.484-4.02-4.5-4.125z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
        <path
          d="M14.86 9.75l-5.054 6-2.165-2.4"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCloudDoneOutline;
