// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCloudOfflineOutline = (props: IconProps) => (
  <Icon
    title={'SvgCloudOfflineOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M21.93 17.707c.816-.677 1.32-1.694 1.32-3.082 0-2.804-2.484-4.02-4.5-4.125-.417-4.197-3.328-6.75-6.75-6.75-1.226 0-2.287.325-3.169.85M4.393 8.59C2.32 9.284.75 10.927.75 13.5c0 3.094 2.531 5.25 5.625 5.25h8.642L4.393 8.59z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M21 21L3 3"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
      </svg>
    }
  />
);

export default SvgCloudOfflineOutline;
