// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCloudDownloadOutline = (props: IconProps) => (
  <Icon
    title={'SvgCloudDownloadOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M9 18.755l3 2.995 3-2.995M12 10.5v10.501m3-5.251h3.563c2.578 0 4.687-.994 4.687-3.544s-2.484-3.444-4.5-3.543C18.333 4.675 15.422 2.25 12 2.25c-3.234 0-5.317 2.146-6 4.275C3.187 6.792.75 8.207.75 11.137c0 2.931 2.531 4.613 5.625 4.613H15z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCloudDownloadOutline;
