// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCodeOutline = (props: IconProps) => (
  <Icon
    title={'SvgCodeOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M7.5 17.25L1.5 12l6-5.25m9 10.5l6-5.25-6-5.25"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCodeOutline;
