// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCompassOutline = (props: IconProps) => (
  <Icon
    title={'SvgCompassOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M21.4 12c0-5.19-4.21-9.4-9.4-9.4S2.6 6.81 2.6 12s4.21 9.4 9.4 9.4 9.4-4.21 9.4-9.4z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeMiterlimit={10}
        />
        <path
          d="M16.635 6.856L10.897 9.15a3.134 3.134 0 00-1.746 1.746l-2.295 5.738a.391.391 0 00.51.509l5.737-2.295a3.132 3.132 0 001.746-1.746l2.295-5.738a.392.392 0 00-.51-.51zM12 13.175a1.175 1.175 0 110-2.35 1.175 1.175 0 010 2.35z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgCompassOutline;
