// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgContactOutline = (props: IconProps) => (
  <Icon
    title={'SvgContactOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M7.873 14.067a2.067 2.067 0 10-4.133 0v2.066a2.067 2.067 0 104.133 0v-2.066zM20.273 14.067a2.067 2.067 0 10-4.133 0v2.066a2.067 2.067 0 004.133 0v-2.066z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M3.74 14.067v-3.1a8.267 8.267 0 1116.533 0v3.1M18.207 18.2c0 .822-.654 1.61-1.816 2.192-1.163.581-2.74.908-4.384.908"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgContactOutline;
