// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgContractOutline = (props: IconProps) => (
  <Icon
    title={'SvgContractOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M14.25 19.5v-5.25h5.25m-4.772.48l5.522 5.52M9.75 4.5v5.25H4.5m4.772-.48L3.75 3.75m15.75 6h-5.25V4.5m.48 4.772l5.52-5.522M4.5 14.25h5.25v5.25m-.48-4.772L3.75 20.25"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgContractOutline;
