// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCopyOutline = (props: IconProps) => (
  <Icon
    title={'SvgCopyOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M19.078 6H8.672A2.672 2.672 0 006 8.672v10.406a2.672 2.672 0 002.672 2.672h10.406a2.672 2.672 0 002.672-2.672V8.672A2.672 2.672 0 0019.078 6z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
        <path
          d="M17.977 6L18 4.875a2.633 2.633 0 00-2.625-2.625H5.25a3.009 3.009 0 00-3 3v10.125A2.633 2.633 0 004.875 18H6"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgCopyOutline;
