// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgCreateWriteOutline = (props: IconProps) => (
  <Icon
    title={'SvgCreateWriteOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M18 10.5v8.625A1.875 1.875 0 0116.125 21H4.875A1.875 1.875 0 013 19.125V7.875A1.875 1.875 0 014.875 6h7.85"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M21.56 2.496a.752.752 0 00-1.089-.026l-.58.577a.375.375 0 000 .53l.532.53a.376.376 0 00.531 0l.566-.562a.762.762 0 00.04-1.049zM18.718 4.22l-8.462 8.447a.42.42 0 00-.108.184l-.392 1.166a.183.183 0 00.228.227l1.165-.391a.422.422 0 00.184-.108l8.447-8.463a.422.422 0 000-.594l-.466-.468a.422.422 0 00-.596 0z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgCreateWriteOutline;
