// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgDislikeOutline = (props: IconProps) => (
  <Icon
    title={'SvgDislikeOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M2.8 9.836a3 3 0 003 3h.054a2 2 0 011.853 1.247l2.605 6.41c.174.427.59.707 1.051.707v0a2.268 2.268 0 002.254-2.521l-.28-2.503a1.5 1.5 0 011.49-1.667h2.696a3 3 0 002.938-3.602l-1.17-5.71A3 3 0 0016.352 2.8H5.8a3 3 0 00-3 3v4.036zM7.6 13.672V2.8"
          stroke="currentColor"
          strokeWidth={1.3}
        />
      </svg>
    }
  />
);

export default SvgDislikeOutline;
