// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgDocumentTextOutline = (props: IconProps) => (
  <Icon
    title={'SvgDocumentTextOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M19.5 10.371V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5v-15a2.25 2.25 0 012.25-2.25h4.629a1.5 1.5 0 011.06.44l6.622 6.62a1.5 1.5 0 01.439 1.061z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinejoin="round"
        />
        <path
          d="M8.25 17.25h7.5M12 2.625V8.25a1.5 1.5 0 001.5 1.5h5.625L12 2.625zM8.25 13.5h7.5-7.5z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgDocumentTextOutline;
