// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgDropdownSolid = (props: IconProps) => (
  <Icon
    title={'SvgDropdownSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12.368 17.297l6.53-9.43c.243-.352.024-.867-.368-.867H5.47c-.392 0-.61.515-.368.867l6.53 9.43c.187.27.549.27.736 0z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgDropdownSolid;
