// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgExitLogoutOutline = (props: IconProps) => (
  <Icon
    title={'SvgExitLogoutOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M18 8.25L21.75 12m0 0L18 15.75M21.75 12H8.953M15 8.25V6.375A1.875 1.875 0 0013.125 4.5h-9A1.875 1.875 0 002.25 6.375v11.25A1.875 1.875 0 004.125 19.5h9A1.875 1.875 0 0015 17.625V8.25z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgExitLogoutOutline;
