// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgExpandOutline = (props: IconProps) => (
  <Icon
    title={'SvgExpandOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M20.25 15v5.25H15m4.772-.48l-5.522-5.52M3.75 9V3.75H9m-4.772.48L9.75 9.75m5.25-6h5.25V9m-.48-4.772L14.25 9.75M9 20.25H3.75V15m.48 4.772l5.52-5.522"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgExpandOutline;
