// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgEyeOffOutline = (props: IconProps) => (
  <Icon
    title={'SvgEyeOffOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M13.735 13.735a2.455 2.455 0 11-3.47-3.47m6.595 6.595A8.24 8.24 0 0112 18.546C6.273 18.546 3 12 3 12a15.096 15.096 0 014.14-4.86l9.72 9.72zM10.282 5.65A7.462 7.462 0 0112 5.456c5.727 0 9 6.545 9 6.545a15.14 15.14 0 01-1.767 2.61l-8.951-8.96zM3 3l18 18"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgEyeOffOutline;
