// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgEyeOnOutline = (props: IconProps) => (
  <Icon
    title={'SvgEyeOnOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M3.265 13.075c-.59-1.028-.614-1.053 0-2.123C5.252 7.491 8.43 5.25 12.011 5.25c3.58 0 6.759 2.241 8.745 5.701.615 1.07.605 1.07 0 2.124-1.986 3.46-5.164 5.701-8.745 5.701-3.581 0-6.76-2.24-8.746-5.7z"
          stroke="currentColor"
          strokeWidth={1.2}
        />
        <circle
          cx={12.01}
          cy={12.013}
          r={2.536}
          stroke="currentColor"
          strokeWidth={1.2}
        />
      </svg>
    }
  />
);

export default SvgEyeOnOutline;
