// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgFaqOutline = (props: IconProps) => (
  <Icon
    title={'SvgFaqOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M19.825 14.888c-.045-.16.053-.384.147-.545a7.243 7.243 0 001.328-4.176c.014-4.123-3.465-7.467-7.766-7.467-3.752 0-6.881 2.553-7.615 5.942a7.185 7.185 0 00-.165 1.53c0 4.126 3.344 7.56 7.646 7.56.684 0 1.605-.206 2.11-.344a14.18 14.18 0 001.136-.371 1.184 1.184 0 01.867.013l2.535.899a.605.605 0 00.175.045.357.357 0 00.357-.358.57.57 0 00-.022-.12l-.733-2.608z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
        <path
          d="M3.525 10.927a6.539 6.539 0 00.286 6.826c.103.156.162.277.144.358-.018.08-.534 2.766-.534 2.766a.358.358 0 00.121.343.365.365 0 00.361.053l2.513-.983a.702.702 0 01.537.009c.847.33 1.783.536 2.72.536a7.12 7.12 0 003.579-.96"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
      </svg>
    }
  />
);

export default SvgFaqOutline;
