// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgFlashOutline = (props: IconProps) => (
  <Icon
    title={'SvgFlashOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M14.778 1.547L4.5 14.25h6l-1.477 8.12a.11.11 0 00.11.13v0a.11.11 0 00.088-.044L19.5 9.75h-6l1.484-8.121a.114.114 0 00-.028-.09.115.115 0 00-.086-.039v0a.113.113 0 00-.092.047v0z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgFlashOutline;
