// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgFlashOffOutline = (props: IconProps) => (
  <Icon
    title={'SvgFlashOffOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M20.25 21a.748.748 0 01-.53-.22L3.22 4.28a.75.75 0 011.06-1.06l16.5 16.5a.75.75 0 01-.53 1.28zM13.797 3.95l-1.035 5.665a.75.75 0 00.755.885h4.412l-1.799 2.223a.188.188 0 00.013.25l.8.8a.189.189 0 00.218.035.187.187 0 00.061-.05l2.85-3.522a.767.767 0 00.155-.674A.75.75 0 0019.5 9h-5.1l1.322-7.236.006-.042a.865.865 0 00-1.537-.644L9.85 6.443a.188.188 0 00.013.251l.8.8a.186.186 0 00.218.034.187.187 0 00.06-.049l2.855-3.528zM10.21 20.043l1.03-5.658a.75.75 0 00-.754-.884H6.074l1.798-2.223a.188.188 0 00-.013-.25l-.8-.8a.188.188 0 00-.278.014l-2.853 3.523a.767.767 0 00-.154.674A.75.75 0 004.5 15h5.101l-1.316 7.236v.005a.86.86 0 001.523.68l4.341-5.364a.187.187 0 00-.013-.251l-.8-.8a.187.187 0 00-.278.015l-2.85 3.521z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgFlashOffOutline;
