// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgGiftOutline = (props: IconProps) => (
  <Icon
    title={'SvgGiftOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12 4.875V7.5h2.625A2.625 2.625 0 1012 4.875v0zm0 0V7.5H9.375A2.625 2.625 0 1112 4.875v0z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
        <path
          d="M19.5 7.5h-15A1.5 1.5 0 003 9v2.25a1.5 1.5 0 001.5 1.5h15a1.5 1.5 0 001.5-1.5V9a1.5 1.5 0 00-1.5-1.5z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12 7.5v14.25m7.5-9v6.75a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5v-6.75h15z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgGiftOutline;
