// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgGoogleSolid = (props: IconProps) => (
  <Icon
    title={'SvgGoogleSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12 5.867c1.878 0 3.145.81 3.867 1.489L18.689 4.6C16.956 2.989 14.7 2 12 2a9.993 9.993 0 00-8.933 5.511L6.3 10.022c.811-2.41 3.056-4.155 5.7-4.155z"
          fill="#EA4335"
        />
        <path
          d="M21.6 12.222c0-.822-.067-1.422-.211-2.044h-9.39v3.71h5.512c-.111.923-.711 2.312-2.044 3.245l3.155 2.445c1.889-1.745 2.978-4.311 2.978-7.356z"
          fill="#4285F4"
        />
        <path
          d="M6.311 13.978A6.157 6.157 0 015.978 12c0-.689.122-1.356.322-1.978L3.067 7.511A10.009 10.009 0 002 12c0 1.611.389 3.133 1.067 4.489l3.244-2.511z"
          fill="#FBBC05"
        />
        <path
          d="M12 22c2.7 0 4.967-.889 6.622-2.422l-3.155-2.445c-.845.59-1.978 1-3.467 1-2.644 0-4.889-1.744-5.689-4.155l-3.233 2.51C4.722 19.757 8.089 22 12 22z"
          fill="#34A853"
        />
      </svg>
    }
  />
);

export default SvgGoogleSolid;
