// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgGroupUserSolid = (props: IconProps) => (
  <Icon
    title={'SvgGroupUserSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12 11.567a3.044 3.044 0 100-6.087 3.044 3.044 0 000 6.087zM18.087 13.306a2.174 2.174 0 100-4.348 2.174 2.174 0 000 4.348zM5.975 13.306a2.174 2.174 0 100-4.348 2.174 2.174 0 000 4.348zM12 12.437a5.659 5.659 0 00-5.652 5.652c0 .24.195.434.435.434h10.434c.24 0 .435-.194.435-.434A5.659 5.659 0 0012 12.437zM6.724 14.27a3.896 3.896 0 00-.811-.094A3.918 3.918 0 002 18.089c0 .24.195.434.435.434h3.123a1.29 1.29 0 01-.08-.434 6.48 6.48 0 011.246-3.82zM18.087 14.176c-.275 0-.545.037-.811.094a6.48 6.48 0 011.246 3.819c0 .153-.032.298-.08.434h3.123c.24 0 .435-.194.435-.434a3.918 3.918 0 00-3.913-3.913z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgGroupUserSolid;
