// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgHeartOutline = (props: IconProps) => (
  <Icon
    title={'SvgHeartOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M4.282 5.332a5.06 5.06 0 000 7.157l7.665 7.665L12 20.1l.053.053 7.665-7.665a5.06 5.06 0 10-7.157-7.157l-.208.208a.5.5 0 01-.707 0l-.208-.208a5.06 5.06 0 00-7.156 0z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgHeartOutline;
