// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgHomeOutline = (props: IconProps) => (
  <Icon
    title={'SvgHomeOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M3.2 20.8V10.336a.2.2 0 01.075-.156l8.6-6.88a.2.2 0 01.25 0l8.6 6.88a.2.2 0 01.075.156V20.8"
          stroke="currentColor"
          strokeLinecap="round"
        />
      </svg>
    }
  />
);

export default SvgHomeOutline;
