// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgHostExpertOutline = (props: IconProps) => (
  <Icon
    title={'SvgHostExpertOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12.004 12.003v.012M15.254 8.752a4.598 4.598 0 010 6.502M18.506 5.5a9.196 9.196 0 010 13.006M8.748 15.254a4.598 4.598 0 010-6.502M5.494 18.506a9.197 9.197 0 010-13.006"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgHostExpertOutline;
