// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgHourglassOutline = (props: IconProps) => (
  <Icon
    title={'SvgHourglassOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M6.826 21.75h10.349c.928 0 1.666-.764 1.566-1.643-.644-5.67-4.49-5.576-4.49-8.107 0-2.531 3.895-2.39 4.49-8.107.093-.88-.638-1.643-1.566-1.643H6.825c-.928 0-1.657.763-1.566 1.643C5.854 9.61 9.75 9.422 9.75 12c0 2.578-3.846 2.438-4.49 8.107-.1.88.637 1.643 1.566 1.643z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M16.092 20.25H7.928c-.731 0-.937-.844-.425-1.367 1.242-1.258 3.747-2.159 3.747-3.602V10.5c0-.93-1.781-1.64-2.883-3.15-.182-.249-.164-.6.298-.6h6.69c.395 0 .48.348.3.598C14.57 8.859 12.75 9.565 12.75 10.5v4.781c0 1.431 2.611 2.203 3.769 3.603.466.565.303 1.366-.427 1.366z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgHourglassOutline;
