// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgImagePicture2Outline = (props: IconProps) => (
  <Icon
    title={'SvgImagePicture2Outline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M19.5 3.75h-15A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V6a2.25 2.25 0 00-2.25-2.25z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinejoin="round"
        />
        <path
          d="M15.75 9.75a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeMiterlimit={10}
        />
        <path
          d="M14.25 15.74L10 11.498a1.5 1.5 0 00-2.056-.06L2.25 16.5m8.25 3.75l5.782-5.782a1.5 1.5 0 012.02-.093l3.448 2.875"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgImagePicture2Outline;
