// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgImagePictureOutline = (props: IconProps) => (
  <Icon
    title={'SvgImagePictureOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M15.45 7.4h.012M17.75 2.8H6.25A3.45 3.45 0 002.8 6.25v11.5a3.45 3.45 0 003.45 3.45h11.5a3.45 3.45 0 003.45-3.45V6.25a3.45 3.45 0 00-3.45-3.45z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M2.8 15.45l4.6-4.6c.524-.505 1.12-.77 1.725-.77s1.2.265 1.725.77l5.75 5.75"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M14.3 14.3l1.15-1.15c.525-.505 1.12-.77 1.726-.77.605 0 1.2.265 1.725.77l2.3 2.3"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgImagePictureOutline;
