// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgLanguageOutline = (props: IconProps) => (
  <Icon
    title={'SvgLanguageOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M2.25 5.25h13.5M9 3v2.25M12.75 21l4.5-10.5 4.5 10.5m-7.617-3h6.234M13.186 5.25s-1.14 4.406-3.858 7.734C6.61 16.313 3.75 18 3.75 18"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12 15.75s-1.64-1.266-3.375-3.516C6.891 9.984 6 8.25 6 8.25"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgLanguageOutline;
