// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgLayersOutline = (props: IconProps) => (
  <Icon
    title={'SvgLayersOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M7.5 14.462l-3.877 1.74c-.825.374-.825.988 0 1.363l6.938 3.165c.792.36 2.095.36 2.886 0l6.938-3.165c.825-.375.825-.989 0-1.364l-3.747-1.803m3.743-7.946L13.38 3.26c-.759-.347-2.001-.347-2.76 0L3.623 6.452c-.825.375-.825.989 0 1.364l6.938 3.164c.792.36 2.095.36 2.886 0l6.938-3.164c.821-.375.821-.99-.004-1.364z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M7.5 9.585l-3.881 1.742c-.825.375-.825.989 0 1.364l6.937 3.163c.792.361 2.095.361 2.887 0l6.937-3.163c.83-.375.83-.99.005-1.364L16.5 9.585"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgLayersOutline;
