// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgLikeOutline = (props: IconProps) => (
  <Icon
    title={'SvgLikeOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M2.8 14.164a3 3 0 013-3h.054a2 2 0 001.853-1.247l2.605-6.41c.174-.427.59-.707 1.051-.707v0a2.268 2.268 0 012.254 2.521l-.28 2.503a1.5 1.5 0 001.49 1.667h2.696a3 3 0 012.938 3.602l-1.17 5.71a3 3 0 01-2.939 2.397H5.8a3 3 0 01-3-3v-4.036zM7.6 10.327V21.2"
          stroke="currentColor"
          strokeWidth={1.2}
        />
      </svg>
    }
  />
);

export default SvgLikeOutline;
