// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgLoading1Outline = (props: IconProps) => (
  <Icon
    title={'SvgLoading1Outline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12 5.867V2.8M16.343 7.655l2.198-2.197M18.133 12H21.2M16.343 16.345l2.198 2.197M12 18.133V21.2M7.655 16.345l-2.198 2.197M5.866 12H2.8M7.655 7.655L5.457 5.458"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgLoading1Outline;
