// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgLockOutline = (props: IconProps) => (
  <Icon
    title={'SvgLockOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M11.511 7.452H4.696c-.752 0-1.363.61-1.363 1.363v4.089c0 .752.61 1.363 1.363 1.363h6.815c.753 0 1.363-.61 1.363-1.363v-4.09c0-.752-.61-1.362-1.363-1.362z"
          stroke="#596168"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M8.104 11.54a.681.681 0 100-1.362.681.681 0 000 1.363zM5.378 7.452V4.726a2.726 2.726 0 115.452 0v2.726"
          stroke="#596168"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgLockOutline;
