// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgMailOpenOutline = (props: IconProps) => (
  <Icon
    title={'SvgMailOpenOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M18.625 17.25l-6.06-4.713a1.125 1.125 0 00-1.38 0l-6.06 4.713m9.375-3.422L20.875 9m-18 0l6.515 4.922"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M20.7 8.044l-8.19-4.042a1.151 1.151 0 00-1.02 0L3.3 8.044a1.875 1.875 0 00-1.05 1.677v8.654c0 1.035.85 1.875 1.9 1.875h15.702c1.05 0 1.9-.84 1.9-1.875V9.721A1.875 1.875 0 0020.7 8.044v0z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgMailOpenOutline;
