// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgMicOutline = (props: IconProps) => (
  <Icon
    title={'SvgMicOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M9 21h6m3-11.25v1.5c0 3.3-2.7 6-6 6m0 0c-3.3 0-6-2.7-6-6v-1.5m6 7.5V21M12 3a2.985 2.985 0 00-3 3v5.203c0 1.65 1.36 3.047 3 3.047s3-1.36 3-3.047V6c0-1.688-1.313-3-3-3z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgMicOutline;
