// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgMicOffOutline = (props: IconProps) => (
  <Icon
    title={'SvgMicOffOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M20.25 18.75L4.5 3"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
        <path
          d="M18.75 11.25V9.771c0-.403-.31-.75-.714-.77a.75.75 0 00-.786.749v1.5c0 .367-.038.733-.115 1.093a.19.19 0 00.05.173l1.023 1.022a.095.095 0 00.087.025.093.093 0 00.067-.059 6.715 6.715 0 00.388-2.254zM12 16.5a5.267 5.267 0 01-5.25-5.25V9.771c0-.403-.31-.75-.714-.77a.75.75 0 00-.786.749v1.5c0 3.469 2.63 6.334 6 6.708v2.292H9.021c-.404 0-.75.31-.77.714A.75.75 0 009 21.75h5.979c.404 0 .75-.31.77-.714A.75.75 0 0015 20.25h-2.25v-2.292a6.706 6.706 0 002.438-.76.188.188 0 00.042-.298l-.84-.84a.187.187 0 00-.21-.036A5.191 5.191 0 0112 16.5zm0-12.75A2.212 2.212 0 0114.25 6v3.503c0 .05.02.097.055.132l1.285 1.287a.093.093 0 00.144-.015.094.094 0 00.016-.052V6.043c0-2.059-1.64-3.765-3.697-3.793a3.734 3.734 0 00-3.21 1.714.188.188 0 00.026.235l.916.916a.094.094 0 00.152-.03A2.224 2.224 0 0112 3.75z"
          fill="currentColor"
        />
        <path
          d="M9.716 11.386L8.41 10.078a.093.093 0 00-.102-.02.094.094 0 00-.058.087v1.058c0 1 .396 1.958 1.1 2.667a3.681 3.681 0 003.646.994.094.094 0 00.04-.158L11.87 13.54a.191.191 0 00-.114-.054c-1.014-.118-1.85-.958-1.986-1.989a.188.188 0 00-.053-.11z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgMicOffOutline;
