// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgMoonOutline = (props: IconProps) => (
  <Icon
    title={'SvgMoonOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M7.5 6.375c0-1.435.211-2.888.75-4.125-3.583 1.56-6 5.218-6 9.375 0 5.592 4.533 10.125 10.125 10.125 4.157 0 7.816-2.417 9.375-6-1.237.539-2.69.75-4.125.75C12.033 16.5 7.5 11.967 7.5 6.375z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgMoonOutline;
