// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgPaymentVisaSolid = (props: IconProps) => (
  <Icon
    title={'SvgPaymentVisaSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M20.147 19.044H3.853A1.853 1.853 0 012 17.19V6.813C2 5.79 2.83 4.96 3.853 4.96h16.294C21.17 4.96 22 5.79 22 6.813V17.19c0 1.023-.83 1.853-1.853 1.853z"
          fill="#3A66AD"
        />
        <path
          d="M11.15 14.208H10.11l.651-4.001h1.042l-.651 4.001zM9.233 10.207l-.994 2.752-.117-.593-.35-1.799s-.043-.36-.495-.36H5.636l-.02.067s.503.105 1.09.458l.905 3.476h1.085l1.658-4.001H9.233zM17.427 14.208h.956l-.834-4.001h-.838c-.387 0-.48.298-.48.298l-1.554 3.703h1.086l.217-.594h1.324l.123.594zm-1.146-1.415l.547-1.498.308 1.498h-.855zM14.759 11.169l.149-.86s-.46-.174-.938-.174c-.517 0-1.744.226-1.744 1.325 0 1.033 1.44 1.046 1.44 1.589 0 .543-1.292.446-1.718.104l-.155.897s.465.227 1.175.227c.711 0 1.784-.368 1.784-1.37 0-1.04-1.454-1.137-1.454-1.59 0-.451 1.015-.394 1.46-.148z"
          fill="#fff"
        />
        <path
          d="M8.122 12.366l-.35-1.799s-.043-.36-.495-.36H5.636l-.02.068s.79.163 1.546.776c.724.585.96 1.315.96 1.315z"
          fill="#E3A340"
        />
      </svg>
    }
  />
);

export default SvgPaymentVisaSolid;
