// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgPhoneOutline = (props: IconProps) => (
  <Icon
    title={'SvgPhoneOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <g clipPath="url(#phone-outline_svg__clip0)">
          <path
            d="M22.898 17.278l-.385 3.468c-.103.93-.84 1.646-1.771 1.549-2.326-.244-6.912-1.394-11.84-6.323-4.93-4.93-6.08-9.516-6.325-11.842-.097-.93.62-1.668 1.55-1.771l3.467-.385a2 2 0 011.958.995l1.419 2.484a2 2 0 01-.323 2.407l-.637.637c-.473.473-.673 1.154-.387 1.758.34.717.969 1.752 2.105 2.888 1.136 1.136 2.171 1.765 2.887 2.104.605.287 1.286.087 1.759-.386l.637-.637a2 2 0 012.406-.323l2.485 1.42a2 2 0 01.995 1.957z"
            stroke="currentColor"
            strokeWidth={1.2}
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </g>
        <defs>
          <clipPath id="phone-outline_svg__clip0">
            <path fill="#fff" d="M0 0h24v24H0z" />
          </clipPath>
        </defs>
      </svg>
    }
  />
);

export default SvgPhoneOutline;
