// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgPhoneEndSolid = (props: IconProps) => (
  <Icon
    title={'SvgPhoneEndSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M4.447 15.06L2.5 12.625c-.292-.365-.286-.88.065-1.19C3.71 10.43 6.654 8.43 12 8.43c5.346 0 8.292 2 9.435 3.007.352.309.358.824.066 1.19l-1.947 2.432a1 1 0 01-1.044.34l-2.558-.698a1 1 0 01-.737-.964v-1.2c0-.335-.169-.646-.478-.773-.508-.208-1.42-.477-2.736-.477-1.316 0-2.228.27-2.736.477-.31.127-.478.438-.478.772v1.2a1 1 0 01-.737.965l-2.558.698a1 1 0 01-1.044-.34z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgPhoneEndSolid;
