// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgPlaySkipBackOutline = (props: IconProps) => (
  <Icon
    title={'SvgPlaySkipBackOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M18.75 5.203v13.594c0 .817-.797 1.337-1.453.945l-11.62-6.955c-.569-.34-.569-1.234 0-1.574l11.62-6.955c.656-.392 1.453.128 1.453.945z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
        <path
          d="M5.25 3.75v16.5"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
      </svg>
    }
  />
);

export default SvgPlaySkipBackOutline;
