// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgPlayBackOutline = (props: IconProps) => (
  <Icon
    title={'SvgPlayBackOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M22.5 6.821v10.36c0 .622-.61 1.018-1.108.72L12.54 12.6c-.433-.26-.433-.94 0-1.2l8.853-5.297c.499-.3 1.108.096 1.108.718zm-10.714 0v10.36c0 .622-.61 1.018-1.108.72L1.825 12.6c-.433-.26-.433-.94 0-1.2l8.853-5.297c.499-.3 1.108.096 1.108.718z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
      </svg>
    }
  />
);

export default SvgPlayBackOutline;
