// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgPlayForwardOutline = (props: IconProps) => (
  <Icon
    title={'SvgPlayForwardOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M1.5 6.821v10.36c0 .622.61 1.018 1.108.72l8.853-5.298c.433-.259.433-.94 0-1.2L2.608 6.106C2.109 5.803 1.5 6.2 1.5 6.821zm10.714 0v10.36c0 .622.61 1.018 1.108.72l8.853-5.298c.433-.259.433-.94 0-1.2l-8.853-5.297c-.499-.303-1.108.093-1.108.715z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
      </svg>
    }
  />
);

export default SvgPlayForwardOutline;
