// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgRadioOutline = (props: IconProps) => (
  <Icon
    title={'SvgRadioOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12 13.5a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"
          fill="currentColor"
        />
        <path
          d="M8.637 9.012a4.5 4.5 0 000 5.977m6.727 0a4.5 4.5 0 000-5.977m-9.116-2.39a7.875 7.875 0 000 10.756m11.505 0a7.875 7.875 0 000-10.756M20.39 19.5a11.266 11.266 0 000-15M3.61 4.5a11.266 11.266 0 000 15"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgRadioOutline;
