// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgReload2Outline = (props: IconProps) => (
  <Icon
    title={'SvgReload2Outline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M3.4 12a8.587 8.587 0 0115.334-5.312M20.574 12A8.587 8.587 0 015.24 17.312m3.68-.405H4.627V21.2m14.72-18.4v4.293h-4.293"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
        />
      </svg>
    }
  />
);

export default SvgReload2Outline;
