// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgReloadOutline = (props: IconProps) => (
  <Icon
    title={'SvgReloadOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M18.75 6.938l-.99-1.152A8.973 8.973 0 0011.25 3c-4.969 0-9 4.031-9 9s4.031 9 9 9a9.004 9.004 0 008.488-6"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
          strokeLinecap="round"
        />
        <path
          d="M21.75 4.567V9.75a.75.75 0 01-.75.75h-5.184a.75.75 0 01-.53-1.28l5.184-5.184a.75.75 0 011.28.53z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgReloadOutline;
