// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgRocketOutline = (props: IconProps) => (
  <Icon
    title={'SvgRocketOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M21.647 2.522a.206.206 0 00-.154-.159c-2.55-.623-8.438 1.598-11.631 4.79A13.823 13.823 0 008.31 8.984c-.984-.089-1.968-.014-2.806.352-2.367 1.04-3.056 3.758-3.248 4.925a.422.422 0 00.46.488l3.8-.418c.002.287.02.573.051.858.02.197.108.381.249.52l1.471 1.472a.85.85 0 00.52.248c.284.032.568.049.853.052l-.417 3.796a.422.422 0 00.487.46c1.168-.188 3.89-.877 4.925-3.243.366-.84.441-1.818.357-2.798a13.775 13.775 0 001.837-1.551c3.205-3.188 5.412-8.947 4.798-11.623zM14 10.016a2 2 0 112.828-2.83A2 2 0 0114 10.016v0z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M5.14 16.5c-.468.057-.903.27-1.236.602C3.078 17.93 3 21 3 21s3.071-.078 3.898-.905c.334-.333.546-.768.602-1.236"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgRocketOutline;
