// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgSettingsOutline = (props: IconProps) => (
  <Icon
    title={'SvgSettingsOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12.295 9.015a3 3 0 10-.59 5.97 3 3 0 00.59-5.97v0zM19.518 12a7.221 7.221 0 01-.072.975l2.12 1.662a.506.506 0 01.115.644l-2.005 3.469a.507.507 0 01-.616.215l-2.105-.847a.753.753 0 00-.711.082 7.703 7.703 0 01-1.01.588.747.747 0 00-.413.569l-.316 2.244a.52.52 0 01-.5.43h-4.01a.52.52 0 01-.501-.415l-.315-2.242a.753.753 0 00-.422-.573 7.278 7.278 0 01-1.006-.59.75.75 0 00-.708-.08l-2.104.848a.507.507 0 01-.616-.215l-2.005-3.469a.506.506 0 01.115-.644l1.79-1.406a.752.752 0 00.282-.66 6.389 6.389 0 010-1.165.75.75 0 00-.284-.654L2.43 9.36a.507.507 0 01-.112-.641L4.324 5.25a.507.507 0 01.616-.215l2.105.847a.755.755 0 00.71-.082 7.71 7.71 0 011.01-.587.747.747 0 00.414-.57L9.494 2.4a.52.52 0 01.501-.43h4.01a.52.52 0 01.5.416l.316 2.241a.753.753 0 00.422.573c.35.17.687.366 1.006.59a.75.75 0 00.708.08l2.104-.848a.507.507 0 01.616.215l2.005 3.469a.506.506 0 01-.115.644l-1.791 1.406a.752.752 0 00-.284.66c.016.195.026.39.026.585z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgSettingsOutline;
