// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgSocialFacebookSolid = (props: IconProps) => (
  <Icon
    title={'SvgSocialFacebookSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 52 52"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <g filter="url(#social-facebook-solid_svg__filter0_dd)">
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M16 18c0-5.523 4.477-10 10-10s10 4.477 10 10-4.477 10-10 10-10-4.477-10-10zm11.042 5.88v-5.44h1.502l.2-1.876h-1.702l.003-.938c0-.489.046-.751.749-.751h.939V13H27.23c-1.804 0-2.439.91-2.439 2.439v1.126h-1.124v1.874h1.124v5.44h2.251z"
            fill="currentColor"
          />
        </g>
        <defs>
          <filter
            id="social-facebook-solid_svg__filter0_dd"
            x={-2}
            y={-2}
            width={56}
            height={56}
            filterUnits="userSpaceOnUse"
            colorInterpolationFilters="sRGB"
          >
            <feFlood floodOpacity={0} result="BackgroundImageFix" />
            <feColorMatrix
              in="SourceAlpha"
              values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            />
            <feOffset dy={8} />
            <feGaussianBlur stdDeviation={8} />
            <feColorMatrix values="0 0 0 0 0.188235 0 0 0 0 0.192157 0 0 0 0 0.2 0 0 0 0.1 0" />
            <feBlend in2="BackgroundImageFix" result="effect1_dropShadow" />
            <feColorMatrix
              in="SourceAlpha"
              values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            />
            <feOffset />
            <feGaussianBlur stdDeviation={0.5} />
            <feColorMatrix values="0 0 0 0 0.188235 0 0 0 0 0.192157 0 0 0 0 0.2 0 0 0 0.05 0" />
            <feBlend in2="effect1_dropShadow" result="effect2_dropShadow" />
            <feBlend
              in="SourceGraphic"
              in2="effect2_dropShadow"
              result="shape"
            />
          </filter>
        </defs>
      </svg>
    }
  />
);

export default SvgSocialFacebookSolid;
