// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgStarOutline = (props: IconProps) => (
  <Icon
    title={'SvgStarOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12.006 17.759l-5.686 2.99 1.086-6.333L2.8 9.932l6.357-.921L12 3.25l2.843 5.76 6.357.922-4.607 4.484 1.087 6.332-5.674-2.99z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgStarOutline;
