// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgStarSolid = (props: IconProps) => (
  <Icon
    title={'SvgStarSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 41 40"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path fill="#fff" d="M.5 0h40v40H.5z" />
        <path
          d="M20.51 29.597l-9.477 4.982 1.81-10.553-7.677-7.473 10.595-1.536L20.5 5.416l4.738 9.601 10.595 1.536-7.677 7.473 1.81 10.553-9.456-4.982z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgStarSolid;
