// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgStudiedEducateSolid = (props: IconProps) => (
  <Icon
    title={'SvgStudiedEducateSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M13.284 15.865a2.484 2.484 0 01-1.284.339c-.472 0-.928-.12-1.284-.339l-5.811-3.564s-.525-.322-.525.407v3.558c0 1.876 3.412 3.897 7.62 3.897s7.62-2.021 7.62-3.896v-.25-3.51c0-.585-.373-.299-.373-.299l-5.963 3.657z"
          fill="currentColor"
        />
        <path
          d="M21.665 9.466c.447-.274.447-.722 0-.996l-8.853-4.427c-.447-.274-1.177-.274-1.624 0L2.335 8.47c-.447.274-.447.722 0 .996l8.853 5.43c.447.273 1.177.273 1.624 0M21.299 17.514v-5.997s.004-.284-.165-.19c-.135.075-.466.26-.583.361-.135.117-.104.38-.104.38v5.446c0 .077-.067.114-.098.133a1.034 1.034 0 00.524 1.928 1.036 1.036 0 00.52-1.93c-.03-.018-.094-.054-.094-.131z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgStudiedEducateSolid;
