// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgSuitcaseSolid = (props: IconProps) => (
  <Icon
    title={'SvgSuitcaseSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 20 20"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12 6.335a.667.667 0 01-.666-.667v-1H8.667v1a.667.667 0 01-1.333 0v-1c0-.735.598-1.333 1.333-1.333h2.667c.735 0 1.333.598 1.333 1.333v1a.667.667 0 01-.666.667zM10.473 12.255a1.46 1.46 0 01-.987-.013L2 9.748v5.087c0 1.013.82 1.833 1.833 1.833h12.334c1.013 0 1.833-.82 1.833-1.833V9.748l-7.527 2.507z"
          fill="currentColor"
        />
        <path
          d="M18 7.168v1.527l-7.84 2.613a.448.448 0 01-.16.027.448.448 0 01-.16-.027L2 8.695V7.168c0-1.013.82-1.833 1.833-1.833h12.334c1.013 0 1.833.82 1.833 1.833z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgSuitcaseSolid;
