// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgThreeDotsHorizoneOutline = (props: IconProps) => (
  <Icon
    title={'SvgThreeDotsHorizoneOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M3.895 13.89a1.895 1.895 0 100-3.79 1.895 1.895 0 000 3.79zm8.105 0a1.895 1.895 0 100-3.79 1.895 1.895 0 000 3.79zm8.105 0a1.895 1.895 0 100-3.79 1.895 1.895 0 000 3.79z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgThreeDotsHorizoneOutline;
