// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgThreeDotsOutline = (props: IconProps) => (
  <Icon
    title={'SvgThreeDotsOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M13.582 19.419a1.581 1.581 0 10-3.162 0 1.581 1.581 0 003.162 0zm0-7.419a1.581 1.581 0 10-3.162 0 1.581 1.581 0 003.162 0zm0-7.419a1.581 1.581 0 10-3.162 0 1.581 1.581 0 003.162 0z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgThreeDotsOutline;
