// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgTimeClockSolid = (props: IconProps) => (
  <Icon
    title={'SvgTimeClockSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <circle cx={12} cy={12} r={10} fill="currentColor" />
        <path
          d="M12 7.455v5.454l2.273 2.273"
          stroke="#fff"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgTimeClockSolid;
