// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgTimeClockOutline = (props: IconProps) => (
  <Icon
    title={'SvgTimeClockOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <circle
          cx={12}
          cy={12}
          r={9.2}
          stroke="currentColor"
          strokeWidth={1.2}
        />
        <path
          d="M12 7.818v5.018l2.091 2.091"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgTimeClockOutline;
