// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgTopFlagsOutline = (props: IconProps) => (
  <Icon
    title={'SvgTopFlagsOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12.002 17.979V2.7l7.307 3.321L12 9.343"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12.002 15.322c-3.613 0-7.279 1.793-7.957 5.178-.082.409.175.8.65.8h14.614c.475 0 .731-.392.65-.8-.68-3.385-4.345-5.178-7.957-5.178z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeMiterlimit={10}
        />
      </svg>
    }
  />
);

export default SvgTopFlagsOutline;
