// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgUserSolid = (props: IconProps) => (
  <Icon
    title={'SvgUserSolid'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M12 11.333c2.677 0 4.846-2.089 4.846-4.666C16.846 4.089 14.676 2 12 2S7.154 4.09 7.154 6.667s2.17 4.666 4.846 4.666zM12 12.667c-4.962 0-9 3.888-9 8.666 0 .368.31.667.692.667h16.616a.68.68 0 00.692-.667c0-4.778-4.038-8.666-9-8.666z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgUserSolid;
