// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgUserOutline = (props: IconProps) => (
  <Icon
    title={'SvgUserOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M3.51 21.2l.137-.883c.209-1.34 1.083-2.49 2.381-2.883 1.499-.454 3.667-.952 5.974-.952 2.308 0 4.476.498 5.974.952 1.299.393 2.173 1.543 2.381 2.883l.138.883M12.001 12.236a4.718 4.718 0 100-9.436 4.718 4.718 0 000 9.436z"
          stroke="currentColor"
          strokeWidth={1.2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    }
  />
);

export default SvgUserOutline;
