// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgVndOutline = (props: IconProps) => (
  <Icon
    title={'SvgVndOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M5.358 14.46l-1.54-4.18H2.52l2.145 5.5H6.04l2.145-5.5H6.887l-1.529 4.18zm6.472-4.323c-.78 0-1.342.286-1.705.847v-.704H8.937v5.5h1.188v-2.948c0-1.067.561-1.584 1.397-1.584.76 0 1.232.451 1.232 1.276v3.256h1.188v-3.377c0-1.408-.847-2.266-2.112-2.266zm8.935-1.342V8.08h-1.188v.715h-1.782v.814h1.782v1.452c-.45-.616-1.089-.924-1.925-.924-.759 0-1.396.275-1.936.836-.538.561-.802 1.243-.802 2.057 0 .803.264 1.496.803 2.057.539.561 1.176.836 1.935.836.836 0 1.474-.308 1.925-.935v.792h1.188V9.609h.715v-.814h-.715zm-4.169 5.5c-.33-.341-.494-.759-.494-1.265 0-.506.165-.924.494-1.254.33-.341.748-.506 1.244-.506.494 0 .913.165 1.242.506.33.33.495.748.495 1.254s-.165.924-.495 1.265c-.33.33-.748.495-1.242.495-.495 0-.913-.165-1.244-.495z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgVndOutline;
