// This component was generated by SVGR.
// Please DO NOT EDIT this file directly, use `yarn build:icon` instead.
import React from 'react';
import { Icon, IconProps } from '@/icon';
const SvgWarningAlertCircleOutline = (props: IconProps) => (
  <Icon
    title={'SvgWarningAlertCircleOutline'}
    {...props}
    children={
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
      >
        <path
          d="M21 12c0-4.969-4.031-9-9-9s-9 4.031-9 9 4.031 9 9 9 9-4.031 9-9z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeMiterlimit={10}
        />
        <path
          d="M11.731 7.784l.27 5.716.268-5.716a.27.27 0 00-.272-.282v0a.269.269 0 00-.266.282v0z"
          stroke="currentColor"
          strokeWidth={1.3}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12 17.246a.937.937 0 110-1.875.937.937 0 010 1.875z"
          fill="currentColor"
        />
      </svg>
    }
  />
);

export default SvgWarningAlertCircleOutline;
