name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v2

      - name: Use node v14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install vercel
        run: npm install -g vercel

      - name: Install  ependencies
        run: yarn install

      - name: Build all
        run: yarn build

      - name: Deploy production
        if: ${{ github.ref == 'refs/heads/master' }}
        working-directory: ./demo/react-site/build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --confirm --no-clipboard --prod)
          echo "::set-output name=deployment_url::$DEPLOYMENT_URL"
      - name: Deploy preview
        if: ${{ github.ref != 'refs/heads/master' }}
        working-directory: ./site/site
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --confirm --no-clipboard)
          echo "::set-output name=deployment_url::$DEPLOYMENT_URL"
      - name: Teardown the deployment
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            This pull request is deployed automatically with Vercel.
            ## web-uikit/site
            ✅ Preview: [${{ steps.deploy.outputs.DEPLOYMENT_URL }}](${{ steps.deploy.outputs.DEPLOYMENT_URL }})
