name: Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v2

      - name: Use node v14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install vercel
        run: npm install -g vercel

      - name: Install core dependencies
        working-directory: ./core
        run: yarn install

      - name: Build core distribution
        working-directory: ./core
        run: yarn build

      - name: Link the core
        working-directory: ./core/dist
        run: yarn link

      - name: Install site dependencies
        working-directory: ./site
        run: yarn install

      - name: Yarn link @pixiepkg/core
        working-directory: ./site
        run: yarn link @pixiepkg/core

      - name: Build site
        working-directory: ./site
        run: yarn build

      - name: Export distribution
        working-directory: ./site
        run: yarn next export

      - name: Deploy production
        if: ${{ github.ref == 'refs/heads/master' }}
        working-directory: ./site
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --confirm --no-clipboard --prod)
          echo "::set-output name=deployment_url::$DEPLOYMENT_URL"

      - name: Deploy preview
        if: ${{ github.ref != 'refs/heads/master' }}
        working-directory: ./site
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --confirm --no-clipboard)
          echo "::set-output name=deployment_url::$DEPLOYMENT_URL"

      - name: Teardown the deployment
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            This pull request is deployed automatically with Vercel.
            ## web-uikit/site
            ✅ Preview: [${{ steps.deploy.outputs.DEPLOYMENT_URL }}](${{ steps.deploy.outputs.DEPLOYMENT_URL }})
